/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import javax.swing.JOptionPane;
import pojos.inventarioFarmacia;

/**
 *
 * @author zof
 */
public class farmacia extends javax.swing.JFrame {

   
    
    //declaracion de objetos 
    inventarioFarmacia central; //se define primer objeto central

   
    
    
    public farmacia() {
        initComponents();
        
    

        central = new inventarioFarmacia(); //genera siempre un objeto

        //datos iniciales  al objeto central
        central.setDisponibles(50); //es llamado el metodo aforo (la cantidad de butacas que se va a tener. El valor inicial es de 20 )

        central.setCosto(45); //llamada a metodo entrada con valor inicial de 8.0

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblmedicamento = new javax.swing.JLabel();
        btnCapturaM = new javax.swing.JButton();
        btnPorVendido = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Farmacias DR Simi");

        jLabel2.setText("Medicamento a vender");

        lblmedicamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        btnCapturaM.setText("Capturar Medicamento");
        btnCapturaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaMActionPerformed(evt);
            }
        });

        btnPorVendido.setText("Porcentaje vendido");
        btnPorVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorVendidoActionPerformed(evt);
            }
        });

        btnVenta.setText("Asignar venta");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        btnIngresos.setText("ingresos");
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblmedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapturaM)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPorVendido)
                .addGap(18, 18, 18)
                .addComponent(btnIngresos)
                .addGap(97, 97, 97))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(btnVenta)
                    .addContainerGap(381, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCapturaM)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblmedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPorVendido)
                    .addComponent(btnIngresos))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(183, Short.MAX_VALUE)
                    .addComponent(btnVenta)
                    .addGap(86, 86, 86)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapturaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaMActionPerformed
        // TODO add your handling code here:
        
             //guardabdo titulo
        String tituloMedicina;

        //abrir ventana para guardar pelicula 
        tituloMedicina = JOptionPane.showInputDialog("Captura el titulo de la pelicula");

        //llamo un objeto para poner el titulo de la pelicula
        central.setMedicamento(tituloMedicina);

        //mandar a imprimir titulo de la pelicula
        this.lblmedicamento.setText(tituloMedicina);
        
    }//GEN-LAST:event_btnCapturaMActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        
        central.medUno();//metodo por cada ingreso 

        JOptionPane.showMessageDialog(null, "Se ha vendido medicamento.");
        
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnPorVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorVendidoActionPerformed
        // TODO add your handling code here:
        
        
        String info; //almacena informacin para mostrar 

        info = "Farmacia \n\n";
        info = info + "Titulo de el medicamento: " + central.getMedicina()+ "\n";
        info = info + "costo: " + central.getCosto()+ "\n";
        info = info + "Vendidas: " + central.getVendidas()+ "\n";

        info = info + "medicinas aún no vendidad " + central.getLibres() + "\n";

        info = info + "Porcentaje de todoEsto: " + central.getPorcentaje() + "\n";

//mandar a imprimir 
        JOptionPane.showMessageDialog(null, info);
        
    }//GEN-LAST:event_btnPorVendidoActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        // TODO add your handling code here:
        
        
         
        String ingresos = ""; // acumula los datos de ingresos
        
        
        ingresos = "Ingresos de medicamentos : \n\n" + central.getIngresos() + "Pesos mexicanos"; //llamada del metodo getIngresos
        JOptionPane.showMessageDialog(null, "Ingresos prodocidos por la sala: \n\n" +ingresos);
        
    }//GEN-LAST:event_btnIngresosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(farmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new farmacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturaM;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnPorVendido;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblmedicamento;
    // End of variables declaration//GEN-END:variables
}
