package vista;

//importacion de clases java en paquete pojos xd 
import javax.swing.JOptionPane;
import pojos.salaCine;

/**
 *
 * @author zof
 */
public class Principal extends javax.swing.JFrame {

    //declaracion de objetos 
    salaCine central; //se define primer objeto central

    public Principal() {  //inicia constructor, termina constructor

        initComponents();

        central = new salaCine(); //genera siempre un objeto

        //datos iniciales  al objeto central
        central.setAforo(50); //es llamado el metodo aforo (la cantidad de butacas que se va a tener. El valor inicial es de 20 )

        central.setEntrada(45); //llamada a metodo entrada con valor inicial de 8.0

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        btnCaptura = new javax.swing.JButton();
        btnOcupacion = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setText("Sala de cines cinepolis Zuñiga");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Película");

        lblPelicula.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPelicula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 5));

        btnCaptura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCaptura.setText("Capturar película");
        btnCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaActionPerformed(evt);
            }
        });

        btnOcupacion.setText("Porcentaje de ocupación");
        btnOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupacionActionPerformed(evt);
            }
        });

        btnAsignar.setText("Asignar Boleto");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LImpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnIngresos.setText("ingresos");
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCaptura)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnAsignar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOcupacion)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addGap(25, 25, 25)
                .addComponent(btnIngresos)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCaptura)))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOcupacion)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAsignar)
                    .addComponent(btnIngresos))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaActionPerformed
        // TODO add your handling code here:

        //guardabdo titulo
        String tituloPelicula;

        //abrir ventana para guardar pelicula 
        tituloPelicula = JOptionPane.showInputDialog("Captura el titulo de la pelicula");

        //llamo un objeto para poner el titulo de la pelicula
        central.setPelicula(tituloPelicula);

        //mandar a imprimir titulo de la pelicula
        this.lblPelicula.setText(tituloPelicula);

    }//GEN-LAST:event_btnCapturaActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        //objeto manda a  llamar todos los  metodos  como un apuntador 

        central.entradaUno(); //metodo por cada ingreso 

        JOptionPane.showMessageDialog(null, "Se ha ocupado un lugar.");


    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupacionActionPerformed
        String info; //almacena informacin para mostrar 

        info = "Sala cine central \n\n";
        info = info + "Titulo de la pelicula: " + central.getPelicula() + "\n";
        info = info + "Aforo: " + central.getAforo() + "\n";
        info = info + "Ocupadas: " + central.getOcupadas() + "\n";

        info = info + "Lugares Libres " + central.getLibres() + "\n";

        info = info + "Porcentaje de ocupacion: " + central.getPorcentaje() + "\n";

//mandar a imprimir 
        JOptionPane.showMessageDialog(null, info);


    }//GEN-LAST:event_btnOcupacionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            // Se elimina el registro de memoria        
        
        central.vaciarCeldas(); //llamada al metodo vaciar
            this.lblPelicula.setText(null); //limpia componente
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        // TODO add your handling code here:
        
        String info = ""; // acumula los datos de ingresos
        
        
        info = "Ingresos de salas : \n\n" + central.getIngresos() + "Pesos mexicanos"; //llamada del metodo getIngresos
        JOptionPane.showMessageDialog(null, "Ingresos prodocidos por la sala: \n\n" +info);
    }//GEN-LAST:event_btnIngresosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCaptura;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnOcupacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
