
package vista;


import pojos.gato;
import pojos.aves;
import pojos.perros;

public class testPruebaMascotas extends javax.swing.JFrame {

   
    public testPruebaMascotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTienda = new javax.swing.JLabel();
        btnGatos = new javax.swing.JButton();
        btnAves = new javax.swing.JButton();
        btnCaninos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTienda.setText("Tienda +kota");

        btnGatos.setText("Consulta Gatos");
        btnGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGatosActionPerformed(evt);
            }
        });

        btnAves.setText("Consulta Aves");
        btnAves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvesActionPerformed(evt);
            }
        });

        btnCaninos.setText("Consulta Caninos");
        btnCaninos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaninosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblTienda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCaninos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTienda)
                .addGap(56, 56, 56)
                .addComponent(btnGatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAves)
                .addGap(12, 12, 12)
                .addComponent(btnCaninos)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGatosActionPerformed
        
        
        gato mascotaUno = new gato("Negro", 5 , "Whiskas", 1.1);
        
        mascotaUno.imprimirDatosGatos();
        
         gato mascotaDos = new gato("Persa", 7 , "Whiskas Premium", 1.2);
        
        mascotaDos.imprimirDatosGatos();
        
        
    }//GEN-LAST:event_btnGatosActionPerformed

    private void btnAvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvesActionPerformed
        
        aves aveUno = new aves("Rojo", "Mexicana");
        aveUno.imprimirAves();
        
          aves aveDos = new aves("Azul", "Brasil");
        aveDos.imprimirAves();
        
        
        
        
    }//GEN-LAST:event_btnAvesActionPerformed

    private void btnCaninosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaninosActionPerformed
        
        
            perros perroUno = new perros("Peluchin", "Dog Chow", 1);
            perroUno.imprimirPerros();
            
             perros perroDos = new perros("Fideo", "pedigry", 2);
            perroDos.imprimirPerros();
        
    }//GEN-LAST:event_btnCaninosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testPruebaMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testPruebaMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testPruebaMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testPruebaMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testPruebaMascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAves;
    private javax.swing.JButton btnCaninos;
    private javax.swing.JButton btnGatos;
    private javax.swing.JLabel lblTienda;
    // End of variables declaration//GEN-END:variables
}
